TWILIO_ACCOUNT_SID ='tienesbuscartuscredencialesalmomentoderegistroentwilio'
TWILIO_AUTH_TOKEN ='tienesbuscartutokenalmomentoderegistroentwilio'
PHONE_NUMBER ='tienesquecomprartunumero'
API_KEY_WAPI = 'tienesbuscartuscredencialesalmomentoderegistroenweatherapi'
